### ISSUE TITLE
Description problem

### ISSUE THREAD

**Issue by laik** [doyoubi/undermoon#106]
Hi, I don't see any special use of this agent from the documentation.Can you explain it to me carefully?
email: laik.lj@me.com

**Comment by doyoubi** [comment]
This is another implementation of [Redis Cluster](https://redis.io/topics/cluster-tutorial) for easier operation. This project provides a cluster solution for Redis just as Redis Cluster.

Further, you can use this project to build a Redis Cluster Cloud for multiple users.

I used the official Redis Cluster massively in the past few years. It's not easy to maintain the official Redis Cluster especially when it comes to large scale management.

I build this to make cluster techniques more accessible for most Redis users.

Hopefully this project will finally settle down to a stable version at the end of April.
I will add more documentation on it in the coming two months.

Thanks for getting to know this project.

**Comment by doyoubi** [comment]
Hi @laik ,

I have updated the docs.
You can take a look at the `README.md` and feel free to let me know if you have any questions.
